# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acc0f0a29961023f3448ec4b73036978db898d1a648febe4541e48939c3e2e2dd94eeed848101ffada010f5deec36de1d0b55e5b5c1a9c476636bf1ef616d61a

test:
  secret_key_base: 37ff31ffb5bbbe20a20cf14407aee97f17c5b06f54ed7182dfcfea0c47f9ecef02443b522a3f12bed663806b4255a38b9381a17a9a554555372a523d814c8d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
